# Generated by Django 4.2.7 on 2023-11-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_contact_bankaccount_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='VendorAddress',
        ),
    ]
