# Generated by Django 4.2.7 on 2023-11-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_address_vendoraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vendoraddress',
            name='created_at',
        ),
    ]
