# Generated by Django 4.2.7 on 2023-11-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_vendor_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankAccount',
            new_name='VendorAccount',
        ),
    ]
