# Generated by Django 4.2.7 on 2023-11-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_bankaccount_vendoraccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='VendorContact',
        ),
    ]
