# Generated by Django 4.2.7 on 2023-11-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_rename_contact_vendorcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoraccount',
            name='created_at',
        ),
    ]
