# Generated by Django 4.2.7 on 2023-11-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('stitle', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
            ],
            options={
                'ordering': ['oid', 'title'],
            },
        ),
    ]
