# Generated by Django 4.2.7 on 2023-11-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='contact',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='office',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
