# Generated by Django 4.2.7 on 2023-11-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_office_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='office',
            field=models.ForeignKey(default='100', on_delete=django.db.models.deletion.CASCADE, to='management.office'),
        ),
    ]
