# Generated by Django 4.2.7 on 2023-11-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_approval_unlock_alter_approval_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='office',
        ),
    ]
