# Generated by Django 4.2.7 on 2023-11-11 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_remove_approval_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='office',
            field=models.ForeignKey(default='101', on_delete=django.db.models.deletion.CASCADE, to='management.office'),
        ),
    ]
