# Generated by Django 4.2.7 on 2023-11-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_itemtype_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit',
            new_name='MeasuringUnit',
        ),
        migrations.RenameField(
            model_name='itemtype',
            old_name='type',
            new_name='item_type',
        ),
    ]
