# Generated by Django 4.2.7 on 2023-11-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_rename_unit_measuringunit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartItem',
            fields=[
                ('iid', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('part_no', models.CharField(blank=True, max_length=50, null=True)),
                ('rev_part', models.CharField(blank=True, max_length=50, null=True)),
                ('part_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='management.itemtype')),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.measuringunit')),
            ],
            options={
                'ordering': ['iid', 'part_no', 'part_name'],
            },
        ),
    ]
