# Generated by Django 4.2.7 on 2023-11-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_partitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partitem',
            options={'ordering': ['id', 'part_no', 'part_name']},
        ),
        migrations.RenameField(
            model_name='partitem',
            old_name='iid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='partitem',
            old_name='type',
            new_name='item_type',
        ),
    ]
