# Generated by Django 4.2.7 on 2023-11-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_titleitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titleitem',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='titleitem',
            old_name='tid',
            new_name='id',
        ),
    ]
