# Generated by Django 4.2.7 on 2023-11-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_alter_titleitem_options_rename_tid_titleitem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
