# Generated by Django 4.2.7 on 2023-11-11 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_quotation_delete_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, default=1, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vat', models.DecimalField(decimal_places=2, default=7.5, max_digits=15)),
                ('ait', models.DecimalField(decimal_places=2, default=3.0, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.partitem')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.quotation')),
            ],
        ),
    ]
