# Generated by Django 4.2.7 on 2023-11-11 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.titleitem')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.title')),
            ],
        ),
    ]
