# Generated by Django 4.2.7 on 2023-11-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_itemintitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('signed', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.vendor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=200)),
                ('recommendation', models.TextField()),
                ('pay_to_company', models.BooleanField(default=False)),
                ('advance', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('security', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('received_on', models.DateField()),
                ('vendor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.vendor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
