# Generated by Django 4.2.7 on 2023-11-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_paymentothersitem_paymentnoteinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.quotation')),
            ],
        ),
        migrations.AlterModelOptions(
            name='paymentnoteinvoice',
            options={'ordering': ['id', 'number']},
        ),
        migrations.CreateModel(
            name='PurchaseOrderTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend', models.CharField(blank=True, max_length=100, null=True)),
                ('newtext', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.purchaseorder')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.termtext')),
            ],
        ),
    ]
