# Generated by Django 4.2.7 on 2023-11-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_paymentothers_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorcontact',
            old_name='designation',
            new_name='title',
        ),
    ]
