# Generated by Django 4.2.7 on 2023-11-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_alter_paymentothersitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['id']},
        ),
    ]
