# Generated by Django 4.2.7 on 2023-11-18 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_office_stitle'),
        ('management', '0035_alter_purchaseorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='office',
            field=models.ForeignKey(default='101', on_delete=django.db.models.deletion.CASCADE, to='hr.office'),
        ),
        migrations.AlterField(
            model_name='paymentnote',
            name='office',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='hr.office'),
        ),
        migrations.AlterField(
            model_name='paymentothers',
            name='office',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='hr.office'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='office',
            field=models.ForeignKey(default='101', on_delete=django.db.models.deletion.CASCADE, to='hr.office'),
        ),
        migrations.DeleteModel(
            name='Office',
        ),
    ]
