# Generated by Django 4.2.7 on 2023-11-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_alter_approval_office_alter_paymentnote_office_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='office',
        ),
    ]
