# Generated by Django 4.2.7 on 2023-11-18 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_rename_title_s_title_stitle'),
        ('management', '0037_remove_approval_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='raise_by',
            field=models.ForeignKey(default='99078', on_delete=django.db.models.deletion.CASCADE, related_name='raised_by', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='approval',
            name='submitted_to',
            field=models.ForeignKey(default='99090', on_delete=django.db.models.deletion.CASCADE, related_name='submiited_to', to='hr.employee'),
        ),
    ]
