# Generated by Django 4.2.7 on 2023-11-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_remove_purchaseorder_office_purchaseorder_order_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderterm',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='termtext',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
