# Generated by Django 4.2.7 on 2023-12-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_rename_title_s_title_stitle'),
        ('management', '0042_paymentnoteapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentnote',
            name='office',
        ),
        migrations.RemoveField(
            model_name='paymentothers',
            name='office',
        ),
        migrations.AddField(
            model_name='paymentnote',
            name='raise_by',
            field=models.ForeignKey(default='99078', on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
        ),
        migrations.AddField(
            model_name='paymentothers',
            name='raise_by',
            field=models.ForeignKey(default='99078', on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
        ),
    ]
