# Generated by Django 4.2.7 on 2023-11-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='parent',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='stitle',
            field=models.CharField(default='100', max_length=10),
        ),
    ]
