# Generated by Django 4.2.7 on 2023-11-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_office_parent_office_stitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='stitle',
            field=models.CharField(max_length=10),
        ),
    ]
