# Generated by Django 4.2.7 on 2023-11-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_office_stitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='title_s',
            new_name='stitle',
        ),
    ]
